image: google/debian:wheezy
env:
  - param={{value}}
publish:
  docker:
    branch: some-branch
    docker_port: 4243
    docker_server: {{docker_server}}
    docker_version: 0.10.0
    email: $$docker_email
    image_name: mohit/temp-container
    password: $$docker_password
    push_latest: false
    registry_login: true
    username: {{docker_username}}
script:
  - make test
  - make build
services:
  - mongo:2.6
